#include <stdio.h>
#include <iostream>
#include <string>
#include <vector>
#include "analyzer.hpp"
#include "lexical_analyzer.hpp"
#include "lexeme.hpp"
#include "parser.hpp"
#include "syntax.h"




int main() {
    // Ask the user to enter a string (one-line only).
    std::string input;
    std::cout << "Enter a string to parse: ";
    std::getline(std::cin, input);
    LexicalAnalyzer analyzer;
    auto lexemes = analyzer.Analyze(input);
    for (auto lexeme : lexemes) {
        std::cout << lexeme.value << " : " << lexeme.GetCategoryString() << std::endl;
    }
    std::vector<Lexeme> incorrectCode;
    std::string result = parseProgram(lexemes, incorrectCode);

    if (result == "") {
        std::cout << "The try program is generated by BNF  grammar for Try Program" << std::endl;
    } else {
        std::cout << "Parsing error: " << result << std::endl;
        std::cout << "The first syntax error is: ";
        for (const auto& lexeme : incorrectCode) {
            std::cout << lexeme.value  << " ";
        }
        std::cout << std::endl;
    }

    return 0;
}




